name: Approval Workflow
on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approve deployment'
        required: true
        default: 'false'

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
    - name: Check approval
      run: |
        if [ "${{ github.event.inputs.approve }}" != "true" ]; then
          echo "Deployment not approved"
          exit 1
        fi