name: Production Workflow  

on:
  push:
    branches: [master]

jobs:

  deploy_prod:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    # Build and push Docker image
    
    # Deploy to Production Fargate service
    
    # Run smoke tests and get approval
  wait-for-approval:
    runs-on: ubuntu-latest
    steps:
    - name: Approval Workflow
      uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: ${{github.repository_owner}}
        repo: ${{github.event.repository.name}}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow_file_name: approval.yml