name: Production Workflow  

on:
  push:
    branches: [master]

jobs:

  deploy_prod:
    runs-on: ubuntu-latest

    permissions:
      issues: write  # Permite crear y editar issues
      workflows: write  # Permite interactuar con workflows, como aprobar
      # Puedes agregar otros permisos según sea necesario, por ejemplo:
      # contents: read  # Permite leer el contenido del repositorio
      pull-requests: write  # Permite interactuar con pull requests

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    # Build and push Docker image
    
    # Deploy to Production Fargate service
    
    # Run smoke tests and get approval
    - name: Request Production Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.MY_SECRET }}  # El secreto configurado
        approvers: "dmsstaging01,jm0077"  # Usuarios que pueden aprobar
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Usamos el GITHUB_TOKEN de forma explícita