name: Production Workflow  

on:
  push:
    branches: [master]

jobs:

  deploy_prod:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    # Build and push Docker image
    
    # Deploy to Production Fargate service
    
    # Run smoke tests and get approval
    - name: Wait for Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: jm0077
        minimum_approvals: 1
        issue-body: "Por favor, revisa y aprueba el despliegue a producción."