name: UAT Workflow

on:
  pull_request:
    branches: [develop]
    
jobs:

  deploy_uat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    # Build and push Docker image
    
    # Deploy to UAT Fargate service
    
    # Run UAT tests and get approval
    - name: Request UAT Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.MY_SECRET }}  # El secreto configurado
        approvers: "user1,user2,jm0077"          # Usuarios que pueden aprobar